/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElL: typeof import('element-plus/es')['ElL']
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const NB: typeof import('naive-ui')['NB']
  const NE: typeof import('naive-ui')['NE']
  const NESTED_TOOLBAR_ICONS: typeof import('naive-ui')['NESTED_TOOLBAR_ICONS']
  const NF: typeof import('naive-ui')['NF']
  const NL: typeof import('naive-ui')['NL']
  const NLoading: typeof import('naive-ui')['NLoading']
  const NM: typeof import('naive-ui')['NM']
  const NN: typeof import('naive-ui')['NN']
  const NU: typeof import('naive-ui')['NU']
  const NV: typeof import('naive-ui')['NV']
}
