name: build
 
# 当提交tag时触发
on:
  push:
    tags:
      - "*"
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'pnpm'

    - name: Install dependencies
      run: 'pnpm i'

    - name: build
      run: pnpm build:mac&&pnpm build:win
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
         dist/*.exe
         dist/*.dmg
         dist/*.exe.blockmap
         dist/latest.yml
         draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}